import os
import google.generativeai as genai

def generate_text(topic, depth, demo_mode):
    if demo_mode:
        return {
            "markdown": f"# {topic} - {depth.capitalize()} Explanation\n\n## Overview\nThis is a **mock explanation** for {topic}. In a real scenario, this would be generated by Google Gemini.\n\n## Key Concepts\n1. **Concept A**: The foundation of {topic}.\n2. **Concept B**: How it interacts with data.\n\n## Learning Objectives\n- Understand the basics of {topic}.\n- Apply concepts to real-world problems.",
            "objectives": ["Understand basics", "Apply concepts", "Debug issues"]
        }

    # Real Implementation
    try:
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            raise ValueError("GEMINI_API_KEY not found")
        
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-pro')
        
        prompt = f"Explain '{topic}' at a {depth} level. Return ONLY valid markdown. Include learning objectives."
        response = model.generate_content(prompt)
        
        return {
            "markdown": response.text,
            "objectives": ["Understand core concepts", "Apply to practice"]
        }
    except Exception as e:
        raise e
